name: Checking
on: push

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

  pylint:
    name: PyLint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: setup

    steps:
      - name: GitHub Action for pylint
        uses: cclauss/GitHub-Action-for-pylint@0.7.0
      # - name: Run PyLint
      #   run: |
      #     pylint

  test:
    name: PyTest
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: setup

    steps:
      - name: Run test suite
        run: |
          pipenv run pytest -v
